Revert "part 1"
This reverts commit 899f0c12a9ce7621c499a5245721678dfa926a76.

diff --git a/src/tsukuri.in b/src/tsukuri.in
--- a/src/tsukuri.in
+++ b/src/tsukuri.in
@@ -1091,24 +1091,24 @@ tsukuri_emerge() {
 		fi	
 	done
 
-	if [ "$(echo $deps | wc -w)" -gt "1" ]; then
-		msg "Overall transaction: "
-		for i in $deps; do
-			printf " [\e[0;31mEMERGE\e[0m] $i $(get_portver $i) \n"
-		done
-	fi
+#	if [ "$(echo $deps | wc -w)" -gt "1" ]; then
+#		msg "Overall transaction: "
+#		for i in $deps; do
+#			printf " [\e[0;31mEMERGE\e[0m] $i $(get_portver $i) \n"
+#		done
+#	fi
 
-	for i in $deps; do
-		pushd "$(get_portdir $i)"
-			(
-				noclean="no" topdir="$PWD" tsukuri_build
-				tsukuri_install
-			)
-			if test $? -ne 0; then
-				die  "Failed to emerge package: $i"
-			fi
-		popd
-	done
+#	for i in $deps; do
+#		pushd "$(get_portdir $i)"
+#			(
+#				noclean="no" topdir="$PWD" tsukuri_build
+#				tsukuri_install
+#			)
+#			if test $? -ne 0; then
+#				die  "Failed to emerge package: $i"
+#			fi
+#		popd
+#	done
 }
 
 list_packages() {
